version: '3.8'
services:

  # PostgreSQL
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartbrain-db
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  # Backend
  smart-brain-api:
    # env_file:
    #   - ./.private/api-keys.env "Another way to insert env variables" 
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/smartbrain-api
    command: npm start
    working_dir: /usr/src/smartbrain-api
    ports:
      - "3001:3001"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartbrain-db
      POSTGRES_HOST: postgres
      REDIS_URI: redis://redis:6379